habr/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.contrib.auth import logout
#from . import views
#from django.views.generic import TemplateView
from habr.views import ( CategoryListView, 
						CategoryDetailView,
						ArticleDetailView,
						CreateCommentView,
						UserReactionView,
						RegistrationView,
						LoginView,
						UserAccountView,
						ArticleCreate,
						AddArticleToFavorites,
						SearchView
						)

urlpatterns = [
    url(r'^$', CategoryListView.as_view(), name='base_view'),
    url(r'^user_account/(?P<user>[-\w]+)/$', UserAccountView.as_view(), name='account_view'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryDetailView.as_view(), name='category-detail'),
	url(r'^add_comment/$', CreateCommentView.as_view(), name='add_comment'),
	url(r'^user_reaction/$', UserReactionView.as_view(), name='user_reaction'),
	url(r'^registration/$', RegistrationView.as_view(), name='registration'),
	url(r'^login_view/$', LoginView.as_view(), name = 'login_view'),
	url(r'^article_create/$', ArticleCreate.as_view(), name='new_post'),
	url(r'^add_to_favorites/$', AddArticleToFavorites.as_view(), name='add_to_favorites'),
	url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('base_view')), name='logout_view'),
	url(r'^search/$', SearchView.as_view(),name='search-view'),
	url(r'^(?P<slug>[-\w]+)/$', ArticleDetailView.as_view(), name='article-detail'),

]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('habr.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

habr/models.py
from django.db import models
from django.urls import reverse
from django.conf.urls import url
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


class Category(models.Model):

	name = models.CharField(max_length=50)
	slug = models.SlugField()

	def __str__(self):
		return self.name


	def get_absolute_url(self):
		return reverse('category-detail', kwargs={'slug': self.slug})

def generic_filename(instance, filename):
	filename = instance.slug + '.jpg'
	return "{0}/{1}".format(instance, filename)


class Article(models.Model):

	author = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
	category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
	title = models.CharField(max_length=120)
	slug = models.SlugField()
	image = models.ImageField(upload_to=generic_filename, blank=True, null=True)
	content = models.TextField()
	likes = models.PositiveIntegerField(default=0)
	comments = GenericRelation('comments')
	users_reaction = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='users_reaction', blank=True)
	
	def __str__(self):

		return self.title

	def get_absolute_url(self):
		return reverse('article-detail', kwargs={'slug': self.slug})



class Comments(models.Model):

	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	comment = models.TextField()
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	content_type = models.ForeignKey(ContentType)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')


class UserAccount(models.Model):

	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	email = models.EmailField()
	favorite_articles = models.ManyToManyField(Article, related_name='favorite_articles')
	my_article = models.ManyToManyField(Article)

	def __str__(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse('account_view', kwargs={'user': user.username})

habr/forms.py
from django import forms
from django.contrib.auth import get_user_model
from habr.models import Article, Category
User = get_user_model()

class CommentForm(forms.Form):

	comment = forms.CharField(widget=forms.Textarea)
	
class LoginForm(forms.Form):

	username = forms.CharField()
	password = forms.CharField(widget = forms.PasswordInput)

	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		user = User.objects.get(username=username)
		if not user.check_password(password):
			raise forms.ValidationError('Құпия сөз қате!')

class RegistrationForm(forms.ModelForm):
	password_check = forms.CharField(widget=forms.PasswordInput)
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = [
			'username',
			'password',
			'password_check',
			'first_name',
			'last_name',
			'email',
		]
	def clean(self):
		password = self.cleaned_data['password']
		password_check = self.cleaned_data['password_check']
		if password != password_check:
			raise forms.ValidationError('Құпия сөздеріңіз сәйкес келмейді!')



class ArticleCreateForm(forms.ModelForm):

	class Meta:
		model = Article
		fields = [
			'category',
			'title',
			'slug',
			'image',
			'content',
		]
	def clean_slug(self):
		new_slug = self.cleaned_data['slug'].lower()
		if new_slug == 'create':
			raise ValidationError('Slug may not be "Create"')
		return new_slug

habr/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import JsonResponse, HttpResponseRedirect
from habr.models import Article, Category, UserAccount
from habr.forms import CommentForm, RegistrationForm, LoginForm, ArticleCreateForm
from django.views import View
from django.urls import reverse
from habr.mixins import CategoryListMixin
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.db.models import Q

User = get_user_model()

class ArticleListView(ListView):

	model = Article
	template_name = 'index.html'

	def get_context_data(self, *args, **kwargs):
		context = super(ArticleListView, self).get_context_data(*args, **kwargs)
		context['articles'] = self.model.objects.all()
		return context

class CategoryListView(ListView):

	model = Category
	template_name = 'index.html'

	def get_context_data(self, *args, **kwargs):
		context = super(CategoryListView, self).get_context_data(*args, **kwargs)
		context['categories'] = self.model.objects.all()
		context['articles'] = Article.objects.all()
		return context


class CategoryDetailView(DetailView, CategoryListMixin):

	model = Category
	template_name = "category_detail.html"

	def get_context_data(self, *args, **kwargs):
		context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
		context['category'] = self.get_object()
		context['articles_from_category'] = self.get_object().article_set.all()
		return context
	
class ArticleDetailView(DetailView, CategoryListMixin):
	
	model = Article
	template_name = "article_detail.html"

	def get_context_data(self, *args, **kwargs):
		context = super(ArticleDetailView, self).get_context_data(*args, **kwargs)
		context['articles'] = self.model.objects.all()
		context['article'] = self.get_object()
		context['article_comments'] = self.get_object().comments.all()
		context['article'] = self.get_object()
		context['form'] = CommentForm()
		context['current_user'] = UserAccount.objects.get(user=self.request.user)

		return context

class ArticleCreate(View, CategoryListMixin):

	template_name = 'new_post.html'

	def get(self, request, *args, **kwargs):
		form = ArticleCreateForm(request.POST or None)
		context = {
			'form': form
		}
		return render(self.request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = ArticleCreateForm(request.POST or None)
		if form.is_valid():
			new_article = form.save(commit=False)
			category = form.cleaned_data['category']
			title = form.cleaned_data['title']
			slug = form.cleaned_data['slug']
			image = form.cleaned_data['image']
			content = form.cleaned_data['content']
			new_article.save()
			Article.objects.create(	   author = request.user,
									   category = new_article.category,
									   title = new_article.title,
									   slug = new_article.slug,
									   image = new_article.image,
									   content = new_article.content)
			return HttpResponseRedirect('/')
		context = {
			'form': form
		}
		return render(self.request, self.template_name, context)

class CreateCommentView(View):

	template_name = 'article_detail.html'

	def post(self, request, *args, **kwargs):
		article_id = self.request.POST.get('article_id')
		comment = self.request.POST.get('comment')
		article = Article.objects.get(id = article_id)
		new_comment = article.comments.create(author=request.user, comment = comment)
		comment = [{ 'author': new_comment.author.username, 'comment' : new_comment.comment, 'timestamp': new_comment.timestamp.strftime('%Y-%m-%d') }]
		return JsonResponse(comment, safe=False)


class UserReactionView(View):

	template_name = 'article_detail.html'

	def get(self, request, *args, **kwargs):
		article_id = self.request.GET.get('article_id')
		article = Article.objects.get(id=article_id)
		like = self.request.GET.get('like')
		if like and (request.user not in article.users_reaction.all()):
			article.likes += 1
			article.users_reaction.add(request.user)
			article.save()
		data = {
			'likes' : article.likes,
		}
		return JsonResponse(data)

class RegistrationView(View, CategoryListMixin):

	template_name = 'registration.html'

	def get(self, request, *args, **kwargs):

		form = RegistrationForm(request.POST or None)
		context = {
			'form': form
		}
		return render(self.request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = RegistrationForm(request.POST or None)
		if form.is_valid():
			new_user = form.save(commit=False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			new_user.set_password(password)
			password_check = form.cleaned_data['password_check']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			new_user.save()
			UserAccount.objects.create(user=User.objects.get(username=new_user.username),
									   first_name=new_user.first_name,
									   last_name = new_user.last_name,
									   email= new_user.email)
			return HttpResponseRedirect('/')
		context = {
			'form': form
		}
		return render(self.request, self.template_name, context)


class LoginView(View, CategoryListMixin):

	template_name = 'login.html'

	def get(self, request, *args, **kwargs):

		form = LoginForm(request.POST or None)
		context = {
			'form': form
		}
		return render(self.request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = LoginForm(request.POST or None)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			if user:
				login(self.request, user)
				return HttpResponseRedirect('/')
		context = {
			'form': form
		}
		return render(self.request, self.template_name, context)

		

class UserAccountView(DetailView, CategoryListMixin):

	template_name = 'user_account.html'

	def get(self, request, *args, **kwargs):
		user = self.kwargs.get('user')
		current_user = UserAccount.objects.get(user=User.objects.get(username=user))
		context = {
			'current_user' : current_user
		}
		return render(self.request, self.template_name, context)


class AddArticleToFavorites(View):
	template_name = 'article_detail.html'

	def get(self, request, *args, **kwargs):
		article_slug = self.request.GET.get('article_slug')
		article = Article.objects.get(slug=article_slug)
		current_user = UserAccount.objects.get(user=request.user)
		current_user.favorite_articles.add(article)
		current_user.save()
		return JsonResponse({'ok':'ok'})


class SearchView(View):

	template_name = 'search.html'

	def get(self, request, *args, **kwargs):
		query = self.request.GET.get('q')
		founded_articles = Article.objects.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query))
		context = {
			'founded_articles': founded_articles
		}
		return render(self.request, self.template_name, context)


habr/templates/article_detail.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block menu %}
<li><a href="{% url 'base_view' %}">Мақалалар</a></li>
<li><a href="#">Пайдаланушылар</a></li>
<li class = 'active'><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded = "false">Хабтар <span class="caret"></span></a>
<ul class="dropdown-menu"> {% for category in categories %}
<li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
{% endfor %}</ul></li>
 {% if not request.user.is_authenticated %}
    <li><a href="{% url 'login_view' %}">Кіру</a></li>
    <li><a href="{% url 'registration' %}">Тіркелу</a></li>
 {% else %}
{% endif %}
{% if request.user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
<li><a href="{% url 'account_view' request.user %}">Жeке парақшам</a></li>
<li><a href="{% url 'logout_view' %}">Шығу</a></li>
</ul>
{% endif %}
{% endblock menu %}

{% block content %}
<div class='container'>
	<div class='col-sm-12'>
		<h1 class="text-center">{{ article.title }}</h1>
		<br>
	<p class="text-center"><img src = '{% if article.image %} {{ article.image.url }} {% endif %}' width="80%"></p>
	<div class="col-sm-12">
	<p style="color:black;font-size: 20px;font-family: Geneva, Arial, Helvetica, sans-serif;"> {{ article.content|safe  }} </p>
	<hr>
	<p style="color:red">Егер мақала ұнаса "ұнады"-ны басыңыз және басқаннан кейін қайтадан алынбайды.</p>
	<a href="#" id="like"><span class="glyphicon glyphicon-thumbs-up" style="color:green"></span></a> <span id="liked">{{ article.likes }}</span>
	<hr>
	<p class="add_to_fovorites-{{ article.slug }}">
		{% if article in current_user.favorite_articles.all %}
		<button class="btn btn-default disabled">Таңдаулыда қосылулы</button>		
		{% else %}
		<a href="#" class="article" data-slug='{{ article.slug }}'><button class="btn btn-danger">Таңдаулыға қосу</button></a>
		{% endif %}
	</p>
	<p class="article_added-{{ article.slug }}"></p>
	<h2>Коментарии:</h2>
	{% for comment in article_comments %}
	<small>{{ comment.author.username }}</small>
	<p>{{ comment.comment }}</p>
	<small>{{ comment.timestamp }}</small>
	<br>
	{% endfor %}
	</div>
	<div class="col-sm-7 col-sm-offset-2">
		<form action="" method="POST">
			<input type="hidden" id="article" data-id='{{ article.id }}'>
			{% csrf_token %}
			{{ form|crispy }}
			<input type="submit" value="Комменатрии қосу" id='add_comment'>
		</form>
		<br><br><br>
	</div>
	</div>
</div>
{% endblock content	%}
{% block jquery %}
<script type="text/javascript">
			$(document).ready(function(){
				function getCookie(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = jQuery.trim(cookies[i]);
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');
		
		$('#add_comment').on('click', function(e){
		e.preventDefault()
		var article_id = $("#article").attr('data-id')
		var comment = $("#id_comment").val()

		data = {
			article_id: article_id,
			comment: comment,
			csrfmiddlewaretoken: csrftoken
		}
		$.ajax({
			type: "POST",
			url: "{% url 'add_comment' %}",
			dataType: 'json',
			data: data,
			succsss: function(data){
				console.log(data)
			}		
		})		
	})
  })
</script>
<script type="text/javascript">
	$(document).ready(function(){

		$('#like').on('click',function(e){
		e.preventDefault()
		var like = 'like'
		var article_id = $('#article').attr('data-id')
		data = {
			article_id: article_id,
			like: like
		}
		$.ajax({
			type: "GET",
			url: "{% url 'user_reaction' %}",
			dataType : 'json',
			data: data,
			success: function(data){
				$('#liked').html(data.likes)
			}
		})
	})
})
</script>

<script>
	$(document).ready(function(){
		$('.article').on('click',function(e){
			e.preventDefault()
			var article_slug = $(this).attr('data-slug')

			data = {
				article_slug: article_slug
			}
			$.ajax({
				type: "GET",
				url: "{% url 'add_to_favorites' %}",
				dataType: "json",
				data:data,
				success: function(data){
					$('.add_to_fovorites-'+article_slug).css('display','none')
					$('.article_added-'+article_slug).html('<button class="btn btn-default disabled">Таңдаулыда қосылулы</button>')
				}
			})
		})
	})
</script>

{% endblock jquery %}

habr/templates/category_detail.html
{% extends 'index.html' %}

{% block menu %}
<li><a href="{% url 'base_view' %}">Мақалалар</a></li>
<li><a href="#">Пайдаланушылар</a></li>
<li class = 'active'><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded = "false">Хабтар <span class="caret"></span></a>
<ul class="dropdown-menu"> {% for category in categories %}
<li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
{% endfor %}</ul></li>
 {% if not request.user.is_authenticated %}
    <li><a href="{% url 'login_view' %}">Кіру</a></li>
    <li><a href="{% url 'registration' %}">Тіркелу</a></li>
 {% else %}
{% endif %}
{% if request.user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
<li><a href="{% url 'account_view' request.user %}">Жeке парақшам</a></li>
<li><a href="{% url 'logout_view' %}">Шығу</a></li>
</ul>
{% endif %}
{% endblock menu %}



{% block content %}
<div class="container">
<h2>Мақалалар : {{ category.name }}</h2>
<hr>
<div class="row">
	{%for article in articles_from_category %}
	{% if article.likes > 0 %}
<div class="col-sm-10" style="margin-bottom: 40px">
	<div class="col-sm-4">
		<img src="{% if article.image %}{{ article.image.url }} {% endif %}" class="img-responsive">
	</div>
	<div class="col-sm-8">
	<div class="text-center">
	<h2>{{ article.title }}</h2>
	<p style="color:black;font-size: 20px;font-family: Geneva, Arial, Helvetica, sans-serif;"> {{ article.content|truncatewords:30 }} </p>
	<a href="{{ article.get_absolute_url }}"><button class="btn btn-primary" style="font-size: 20px" >Толық оқу</button></a>
	</div>
	</div>
</div>
	{% endif %}
	{% endfor %}
</div>
</div>
<br><br>
{% endblock content %}

habr/templates/index.html
<!DOCTYPE>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Хабр</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% load staticfiles %}
  <meta content="" name="keywords">
  <meta content="" name="description">
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900|Raleway:400,300,700,900" rel="stylesheet">
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
  <!-- Fixed navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'base_view' %}">Habr<i class="fa fa-circle"></i>kz</a>
      </div>

      <!-- Меню левый край -->
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          {% block menu %}
          <li class="active"><a href="{% url 'base_view' %}">Мақалалар</a></li>
          <li><a href="#">Пайдаланушылар</a></li>
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded = "false">Хабтар <span class="caret"></span></a>
            <ul class="dropdown-menu">
              {% for category in categories %}
              <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% if not request.user.is_authenticated %}
          <li><a href="{% url 'login_view' %}">Кіру</a></li>
          <li><a href="{% url 'registration' %}">Тіркелу</a></li>
          {% else %}
          {% endif %}
          {% if request.user.is_authenticated %}
          <li><a href="{% url 'account_view' request.user %}">Жeке парақшам</a></li>
          <li><a href="{% url 'logout_view' %}">Шығу</a></li> 
          {% endif %}
          {% endblock menu %}
          </ul>
        <div style="text-align: center">
        <form class="form-inline my-2 my-lg-0" action="{% url 'search-view' %}" method="GET">
          <input style="margin-bottom: 5px" type="input" class="form-control mr-sm-2" placeholder="Керекті мақаланы іздеу" name="q">
          <button style="margin-left:5px;background-color:#ff7878;color:white" class="btn btn-outline-success my-2 my-sm-0">Іздеу</button>
        </form>
        </div>
      </div>
    </div>
  </div>


  <div id="blue">
    <div class="container">
      <div class="row centered">
        <div class="col-lg-8 col-lg-offset-2">
          <h4>ХАБР.KZ</b></h4>
          <p>Қазақстандық айти форум<br>Салеметсизбе, {{ request.user }}</p>
        </div>
      </div>
    </div>
  </div>
{% block content %}
<section>
  <div class="container">
  <div class="top-article">
  <h1>Ең жақсылары : </h1>
  <hr>
<ul>
{% for article in articles %}
{% if article.likes > 0 %}
<div class="col-sm-10" style="margin-bottom: 60px">
  <div class="col-sm-4">
  <img src="{% if article.image %} {{ article.image.url }} {% endif %}" class="img-responsive">
  </div>
  <div class="col-sm-8">
  <div class="text-center">
  <h2>{{ article.title }}</h2>
  <h3>Автор: {{ article.author }}</h4>
  <h3>Категория: {{ article.category }}</h4>
  <p style="color:black;font-size: 20px;font-family: Geneva, Arial, Helvetica, sans-serif;"> {{ article.content|truncatewords:30 }} </p>
  <a href="{{ article.get_absolute_url }}"><button class="btn btn-primary" style="font-size: 20px">Толық оқу</button></a>
  <hr>
  </div>
  </div>
  </div>
{% endif %}
{% endfor %}
</ul>
  </div>
 </div>
</section>
 {% endblock content %}

  <div id="f">
    <div class="container">
      <div class="row centered">
        <a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-vk"></i></a><a href="#"><i class="fa fa-instagram"></i></a>
      </div>
    </div>
  </div>


  <div id="copyrights">
    <div class="container">
      <div class="credits">
        Dala-<a href="#">Soft</a>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  {% block jquery %}
  {% endblock jquery %}

</body>

</html>

habr/templates/login.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block menu %}
<li><a href="{% url 'base_view' %}">Мақалалар</a></li>
<li><a href="#">Пайдаланушылар</a></li>
<li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded = "false">Хабтар <span class="caret"></span></a>
<ul class="dropdown-menu"> {% for category in categories %}
<li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
{% endfor %}</ul></li>
<li class="active"><a href="{% url 'login_view' %}">Кіру</a></li>
<li><a href="{% url 'registration' %}">Тіркелу</a></li>
{% if request.user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
<li><a href="#">Жeке парақшам</a></li>
</ul>
{% endif %}
{% endblock menu %}

{% block content %}
<div class="container">
	<h3 class="text-center">Кіру</h3>
	<hr>
	<div style="margin-bottom: 25%" class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<form action="" method="POST">
				{{ form.error }}
				{% csrf_token %}
				{{ form|crispy }}
				<input style="font-size:20px" class='btn btn-primary' type="submit" value="Кіру">
			</form>
		</div>
	</div>
</div>
{% endblock content %}

habr/templates/new_post.html
{% extends 'index.html' %}
{% block menu %}
<li><a href="{% url 'base_view' %}">Мақалалар</a></li>
<li><a href="#">Пайдаланушылар</a></li>
<li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded = "false">Хабтар <span class="caret"></span></a>
<ul class="dropdown-menu"> {% for category in categories %}
<li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
{% endfor %}</ul></li>
 {% if not request.user.is_authenticated %}
    <li><a href="{% url 'login_view' %}">Кіру</a></li>
    <li><a href="{% url 'registration' %}">Тіркелу</a></li>
 {% else %}
{% endif %}
{% if request.user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
<li class='active'><a href="{% url 'account_view' request.user %}">Жeке парақшам</a></li>
<li><a href="{% url 'logout_view' %}">Шығу</a></li>
</ul>
{% endif %}
{% endblock menu %}

{% load crispy_forms_tags %}
{% block content %}
<br><br><br>
<div class="container">
	<form action="{% url 'new_post' %}" method="post">
		{{ form.error }}
		{% csrf_token %}
		{{ form|crispy }}
		<button style="font-size:20px" id="article" class='btn btn-primary' type='submit'>Жіберу</button>	
	</form>
</div>
{% endblock content %}
{% block jquery %}
<script type="text/javascript">
		$(document).ready(function(){
		$('#article').on('click',function(e){
			alert('Жіберілді, тексерістен өткенсін сайтқа шығады.');
		})
	})
</script>
{% endblock jquery %}

habr/templates/search.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
	<div class="col-sm-12">
		<h2>Табылған нәтижелер: {{ founded_articles.count }}</h2>
		{% for article in founded_articles %}
		<h3><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
		<p>{{ article.content|truncatewords:30 }}</p>
		{% endfor %}
	</div>
</div>	
{% endblock content %}